version: "3"

services:
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.config/traefik/:/config
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    command:
      # - --api.dashboard=true
      # - --accesslog=true
      # - --accesslog.filepath=/var/log/traefik/access.log
      # - --log.level=DEBUG
      # - --log.filepath=/var/log/traefik/traefik.log
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entryPoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --certificatesresolvers.letsencrypt.acme.email=${CLOUDFLARE_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/config/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1,9.9.9.9,8.8.8.8
    #   - --certificatesresolvers.letsencrypt.acme.dnschallenge.disablepropagationcheck=true
    #   - --certificatesresolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.traefik.entrypoints=websecure
    #   - traefik.http.routers.traefik.rule=Host(`dashboard.99linesofcode.nl`)
    #   - traefik.http.routers.traefik.service=api@internal
    #   - traefik.http.routers.traefik.tls.certresolver=letsencrypt

  # whoami:
  #   image: traefik/whoami
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.whoami.entrypoints=websecure
  #     - traefik.http.routers.whoami.rule=Host(`whoami.99linesofcode.nl`)
  #     - traefik.http.routers.whoami.tls.certresolver=letsencrypt

  php:
    build:
      dockerfile: Dockerfile
      context: ..
    environment:
      - SERVER_NAME=${APP_URL}
    # volumes:
    #   - ../laravel-skeleton/frankenphp/Caddyfile:/etc/caddy/Caddyfile
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.php.rule=HostSNI(`${APP_URL}`)
      - traefik.tcp.routers.php.tls.passthrough=true
      - traefik.tcp.services.php.loadbalancer.server.port=443

networks:
  default:
    name: ${APP_NAME}.net
    driver: bridge
