name: analyse

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  analyse:
    uses: 99linesofcode/.github/.github/workflows/analyse.yaml@main
