name: deploy

on:
  push:
    branches:
      - main
      - finalize-deployment

jobs:
  deploy:
    defaults:
      run:
        working-directory: .
    uses: 99linesofcode/.github/.github/workflows/deploy.yml@main
