name: Laravel Tests

on: [push, pull_request]
# on:
#   push:
#     paths:
#       - 'api/**'

jobs:
  tests:
    defaults:
      run:
        working-directory: .
    uses: 99linesofcode/.github/.github/workflows/laravel-test.yml@main
