name: test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    defaults:
      run:
        working-directory: .
    uses: 99linesofcode/.github/.github/workflows/laravel-test.yml@main
