name: test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    uses: 99linesofcode/.github/.github/workflows/laravel-test.yml@main
    with:
      calling_repository_name: ${{ github.repository }}
